keys:
  - &admin_pascal age1t4j0nk2vazgqz2gjulh972kfgjt0awnvd6w6tvvafgkkytpv03us5am70c
  - &host_quill age1960pncsvrglepsagauzkwhdvyhp9qrtwd4c0k23hm9p7xsnjqpaqf7zuq9
creation_rules:
  - path_regex: secrets/quill\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pascal
          - *host_quill
